# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'
            $uploadedPhotosFolder: '/public/uploads/photos'
            $uploadedAvatarsFolder: '/public/uploads/avatars'
            $defaultAvatarFile: 'default_avatar.png'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Service for the Entity User
    App\Service\UserService:
        class: App\Service\UserService

    # Configuration command to email all active users created in the last week
    App\Command\SendEmailsToActiveUsersCommand:
        arguments:
            $mailer: '@Symfony\Component\Mailer\MailerInterface'
            $userService: '@App\Service\UserService'

    # Subscriber used to set a default avatar to each new User created by someone
    # which filled in the login form without uploading an avatar
    App\EventSubscriber\UserSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    # Subscriber to remove the role 'IS_AUTHENTICATED_FULLY' to a user as soon as the
    # duration of a token created after the authentication of this user is over
    App\EventSubscriber\TokenExpirationSubscriber:
        tags:
            - { name: kernel.event_subscriber }